package main

import (
	_ "go-study/docs" // docs is generated by Swag CLI, you have to import it.

	// "go-study/grpcserver"
	// "go-study/study"
	// "go-study/test"
	"go-study/user"
)

// @title Swagger - User API
// @version 1.0
// @description This is api document for user server.

// @contact.name ahnus123
// @contact.url https://github.com/ahnus123/go-study/user
// @contact.email ahnus123@gmail.com

// @license.name gorilla/mux
// @license.url https://github.com/gorilla/mux/blob/master/LICENSE

// @host localhost:12000
// @BasePath
func main() {
	// test
	// test.TestMain()

	// study
	// study.StudyMain()

	// grpcserver
	// grpcserver.GrpcServerMain()

	// user server
	user.UserMain()
}
